version: '3.4'
x-restart-policy: &restart_policy
  restart: unless-stopped
services:
  serve:
    << : *restart_policy
    build: 
      context: ./serve
    # 端口映射
    volumes: 
      - ./serve/src:/code/src
      - ./data:/data
    ports:
        - "8100:3000"
  front:
    << : *restart_policy
    build: 
      context: ./front
      dockerfile: Dockerfile.dev
    volumes: 
      - ./front:/code
      - /code/node_modules/
    ports: 
      - "8101:3000"