version: '3'
services:
  serve:
    build: ./serve
    # 端口映射
    volumes: 
      - ./serve/src:/code/src
      - ./data:/data
    ports:
        - "8100:3000"
  front:
    build: ./front
    volumes: 
      - ./front:/code
      - /code/node_modules/
    ports: 
      - "8101:3000"