version: '3.4'
x-restart-policy: &restart_policy
  restart: unless-stopped
services:
  serve:
    build: ./serve
    # 端口映射
    volumes: 
      - ./serve/src:/code/src
      - ./data:/data
    ports:
        - "9100:3000"
  front:
    build: ./front
    volumes: 
      - ./front:/code
      - /code/node_modules/
    ports: 
      - "9101:3000"